package com.xpg.hssy.db.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.xpg.hssy.db.dao.UserDao;
import com.xpg.hssy.db.dao.PileDao;
import com.xpg.hssy.db.dao.KeyDao;
import com.xpg.hssy.db.dao.ChargeRecordDao;
import com.xpg.hssy.db.dao.ChargeRecordCacheDao;
import com.xpg.hssy.db.dao.ChargeOrderDao;
import com.xpg.hssy.db.dao.ShareTimeDao;
import com.xpg.hssy.db.dao.PileCollectionDao;
import com.xpg.hssy.db.dao.AddressSearchRecodeDao;
import com.xpg.hssy.db.dao.PileSearchRecodeDao;
import com.xpg.hssy.db.dao.DistrictDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 52): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 52;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UserDao.createTable(db, ifNotExists);
        PileDao.createTable(db, ifNotExists);
        KeyDao.createTable(db, ifNotExists);
        ChargeRecordDao.createTable(db, ifNotExists);
        ChargeRecordCacheDao.createTable(db, ifNotExists);
        ChargeOrderDao.createTable(db, ifNotExists);
        ShareTimeDao.createTable(db, ifNotExists);
        PileCollectionDao.createTable(db, ifNotExists);
        AddressSearchRecodeDao.createTable(db, ifNotExists);
        PileSearchRecodeDao.createTable(db, ifNotExists);
        DistrictDataDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UserDao.dropTable(db, ifExists);
        PileDao.dropTable(db, ifExists);
        KeyDao.dropTable(db, ifExists);
        ChargeRecordDao.dropTable(db, ifExists);
        ChargeRecordCacheDao.dropTable(db, ifExists);
        ChargeOrderDao.dropTable(db, ifExists);
        ShareTimeDao.dropTable(db, ifExists);
        PileCollectionDao.dropTable(db, ifExists);
        AddressSearchRecodeDao.dropTable(db, ifExists);
        PileSearchRecodeDao.dropTable(db, ifExists);
        DistrictDataDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UserDao.class);
        registerDaoClass(PileDao.class);
        registerDaoClass(KeyDao.class);
        registerDaoClass(ChargeRecordDao.class);
        registerDaoClass(ChargeRecordCacheDao.class);
        registerDaoClass(ChargeOrderDao.class);
        registerDaoClass(ShareTimeDao.class);
        registerDaoClass(PileCollectionDao.class);
        registerDaoClass(AddressSearchRecodeDao.class);
        registerDaoClass(PileSearchRecodeDao.class);
        registerDaoClass(DistrictDataDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
