package com.xpg.hssy.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xpg.hssy.db.pojo.User;
import com.xpg.hssy.db.pojo.Pile;
import com.xpg.hssy.db.pojo.Key;
import com.xpg.hssy.db.pojo.ChargeRecord;
import com.xpg.hssy.db.pojo.ChargeRecordCache;
import com.xpg.hssy.db.pojo.ChargeOrder;
import com.xpg.hssy.db.pojo.ShareTime;
import com.xpg.hssy.db.pojo.PileCollection;
import com.xpg.hssy.db.pojo.AddressSearchRecode;
import com.xpg.hssy.db.pojo.PileSearchRecode;
import com.xpg.hssy.db.pojo.DistrictData;

import com.xpg.hssy.db.dao.UserDao;
import com.xpg.hssy.db.dao.PileDao;
import com.xpg.hssy.db.dao.KeyDao;
import com.xpg.hssy.db.dao.ChargeRecordDao;
import com.xpg.hssy.db.dao.ChargeRecordCacheDao;
import com.xpg.hssy.db.dao.ChargeOrderDao;
import com.xpg.hssy.db.dao.ShareTimeDao;
import com.xpg.hssy.db.dao.PileCollectionDao;
import com.xpg.hssy.db.dao.AddressSearchRecodeDao;
import com.xpg.hssy.db.dao.PileSearchRecodeDao;
import com.xpg.hssy.db.dao.DistrictDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig pileDaoConfig;
    private final DaoConfig keyDaoConfig;
    private final DaoConfig chargeRecordDaoConfig;
    private final DaoConfig chargeRecordCacheDaoConfig;
    private final DaoConfig chargeOrderDaoConfig;
    private final DaoConfig shareTimeDaoConfig;
    private final DaoConfig pileCollectionDaoConfig;
    private final DaoConfig addressSearchRecodeDaoConfig;
    private final DaoConfig pileSearchRecodeDaoConfig;
    private final DaoConfig districtDataDaoConfig;

    private final UserDao userDao;
    private final PileDao pileDao;
    private final KeyDao keyDao;
    private final ChargeRecordDao chargeRecordDao;
    private final ChargeRecordCacheDao chargeRecordCacheDao;
    private final ChargeOrderDao chargeOrderDao;
    private final ShareTimeDao shareTimeDao;
    private final PileCollectionDao pileCollectionDao;
    private final AddressSearchRecodeDao addressSearchRecodeDao;
    private final PileSearchRecodeDao pileSearchRecodeDao;
    private final DistrictDataDao districtDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        pileDaoConfig = daoConfigMap.get(PileDao.class).clone();
        pileDaoConfig.initIdentityScope(type);

        keyDaoConfig = daoConfigMap.get(KeyDao.class).clone();
        keyDaoConfig.initIdentityScope(type);

        chargeRecordDaoConfig = daoConfigMap.get(ChargeRecordDao.class).clone();
        chargeRecordDaoConfig.initIdentityScope(type);

        chargeRecordCacheDaoConfig = daoConfigMap.get(ChargeRecordCacheDao.class).clone();
        chargeRecordCacheDaoConfig.initIdentityScope(type);

        chargeOrderDaoConfig = daoConfigMap.get(ChargeOrderDao.class).clone();
        chargeOrderDaoConfig.initIdentityScope(type);

        shareTimeDaoConfig = daoConfigMap.get(ShareTimeDao.class).clone();
        shareTimeDaoConfig.initIdentityScope(type);

        pileCollectionDaoConfig = daoConfigMap.get(PileCollectionDao.class).clone();
        pileCollectionDaoConfig.initIdentityScope(type);

        addressSearchRecodeDaoConfig = daoConfigMap.get(AddressSearchRecodeDao.class).clone();
        addressSearchRecodeDaoConfig.initIdentityScope(type);

        pileSearchRecodeDaoConfig = daoConfigMap.get(PileSearchRecodeDao.class).clone();
        pileSearchRecodeDaoConfig.initIdentityScope(type);

        districtDataDaoConfig = daoConfigMap.get(DistrictDataDao.class).clone();
        districtDataDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        pileDao = new PileDao(pileDaoConfig, this);
        keyDao = new KeyDao(keyDaoConfig, this);
        chargeRecordDao = new ChargeRecordDao(chargeRecordDaoConfig, this);
        chargeRecordCacheDao = new ChargeRecordCacheDao(chargeRecordCacheDaoConfig, this);
        chargeOrderDao = new ChargeOrderDao(chargeOrderDaoConfig, this);
        shareTimeDao = new ShareTimeDao(shareTimeDaoConfig, this);
        pileCollectionDao = new PileCollectionDao(pileCollectionDaoConfig, this);
        addressSearchRecodeDao = new AddressSearchRecodeDao(addressSearchRecodeDaoConfig, this);
        pileSearchRecodeDao = new PileSearchRecodeDao(pileSearchRecodeDaoConfig, this);
        districtDataDao = new DistrictDataDao(districtDataDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Pile.class, pileDao);
        registerDao(Key.class, keyDao);
        registerDao(ChargeRecord.class, chargeRecordDao);
        registerDao(ChargeRecordCache.class, chargeRecordCacheDao);
        registerDao(ChargeOrder.class, chargeOrderDao);
        registerDao(ShareTime.class, shareTimeDao);
        registerDao(PileCollection.class, pileCollectionDao);
        registerDao(AddressSearchRecode.class, addressSearchRecodeDao);
        registerDao(PileSearchRecode.class, pileSearchRecodeDao);
        registerDao(DistrictData.class, districtDataDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        pileDaoConfig.getIdentityScope().clear();
        keyDaoConfig.getIdentityScope().clear();
        chargeRecordDaoConfig.getIdentityScope().clear();
        chargeRecordCacheDaoConfig.getIdentityScope().clear();
        chargeOrderDaoConfig.getIdentityScope().clear();
        shareTimeDaoConfig.getIdentityScope().clear();
        pileCollectionDaoConfig.getIdentityScope().clear();
        addressSearchRecodeDaoConfig.getIdentityScope().clear();
        pileSearchRecodeDaoConfig.getIdentityScope().clear();
        districtDataDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PileDao getPileDao() {
        return pileDao;
    }

    public KeyDao getKeyDao() {
        return keyDao;
    }

    public ChargeRecordDao getChargeRecordDao() {
        return chargeRecordDao;
    }

    public ChargeRecordCacheDao getChargeRecordCacheDao() {
        return chargeRecordCacheDao;
    }

    public ChargeOrderDao getChargeOrderDao() {
        return chargeOrderDao;
    }

    public ShareTimeDao getShareTimeDao() {
        return shareTimeDao;
    }

    public PileCollectionDao getPileCollectionDao() {
        return pileCollectionDao;
    }

    public AddressSearchRecodeDao getAddressSearchRecodeDao() {
        return addressSearchRecodeDao;
    }

    public PileSearchRecodeDao getPileSearchRecodeDao() {
        return pileSearchRecodeDao;
    }

    public DistrictDataDao getDistrictDataDao() {
        return districtDataDao;
    }

}
