package com.xpg.hssy.db.pojo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CHARGE_RECORD_CACHE.
 */
public class ChargeRecordCache extends com.xpg.hssy.db.pojo.Record  implements java.io.Serializable {

    private Long id;
    private Integer sequence;
    private String orderId;
    private String userid;
    private String userName;
    private String phoneNo;
    private String pileId;
    private Long startTime;
    private Long endTime;
    private Float quantity;
    private String receipt;
    private Float chargePrice;
    private String data;
    private Integer status;
    private Long createTime;
    private Byte startReason;
    private Byte stopReason;

    // KEEP FIELDS - put your custom fields here
    public static class RecordData
    {
        private  String orderId;
	    private  Integer sequence;
	    private  String userid;
	    private  String pileId;
	    private  Float quantity;
	    private String data;

	    public String getOrderId() {
		    return orderId;
	    }

	    public void setOrderId(String orderId) {
		    this.orderId = orderId;
	    }

	    public Integer getSequence() {
		    return sequence;
	    }

	    public void setSequence(Integer sequence) {
		    this.sequence = sequence;
	    }


	    public String getUserid() {
		    return userid;
	    }

	    public void setUserid(String userid) {
		    this.userid = userid;
	    }

	    public String getPileId() {
		    return pileId;
	    }

	    public void setPileId(String pileId) {
		    this.pileId = pileId;
	    }

	    public Float getQuantity() {
		    return quantity;
	    }

	    public void setQuantity(Float quantity) {
		    this.quantity = quantity;
	    }

	    public String getData() {
		    return data;
	    }

	    public void setData(String data) {
		    this.data = data;
	    }

    }
    // KEEP FIELDS END

    public ChargeRecordCache() {
    }

    public ChargeRecordCache(Long id) {
        this.id = id;
    }

    public ChargeRecordCache(Long id, Integer sequence, String orderId, String userid, String userName, String phoneNo, String pileId, Long startTime, Long endTime, Float quantity, String receipt, Float chargePrice, String data, Integer status, Long createTime, Byte startReason, Byte stopReason) {
        this.id = id;
        this.sequence = sequence;
        this.orderId = orderId;
        this.userid = userid;
        this.userName = userName;
        this.phoneNo = phoneNo;
        this.pileId = pileId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.quantity = quantity;
        this.receipt = receipt;
        this.chargePrice = chargePrice;
        this.data = data;
        this.status = status;
        this.createTime = createTime;
        this.startReason = startReason;
        this.stopReason = stopReason;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPhoneNo() {
        return phoneNo;
    }

    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    public String getPileId() {
        return pileId;
    }

    public void setPileId(String pileId) {
        this.pileId = pileId;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Float getQuantity() {
        return quantity;
    }

    public void setQuantity(Float quantity) {
        this.quantity = quantity;
    }

    public String getReceipt() {
        return receipt;
    }

    public void setReceipt(String receipt) {
        this.receipt = receipt;
    }

    public Float getChargePrice() {
        return chargePrice;
    }

    public void setChargePrice(Float chargePrice) {
        this.chargePrice = chargePrice;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Byte getStartReason() {
        return startReason;
    }

    public void setStartReason(Byte startReason) {
        this.startReason = startReason;
    }

    public Byte getStopReason() {
        return stopReason;
    }

    public void setStopReason(Byte stopReason) {
        this.stopReason = stopReason;
    }

    // KEEP METHODS - put your custom methods here


	@Override
	public boolean equals(Object o) {
		if (null == o || null == pileId || null == startTime || null == endTime || null == sequence || null == data) return false;
		if (o instanceof ChargeRecordCache) {
			ChargeRecordCache cache = (ChargeRecordCache) o;
			return pileId.equals(cache.getPileId()) && startTime.equals(cache.getStartTime()) && endTime.equals(cache.getEndTime()) && sequence.equals(cache
					.getSequence()) &&
					data.equals(cache.getData());
		} else {
			return false;
		}
	}

    @Override
    public int hashCode() {
        StringBuilder strb = new StringBuilder();
        strb.append(pileId).append(startTime).append(endTime).append(sequence).append(data);
        return strb.toString().hashCode();
    }

    public RecordData createRecordForUpload(){
		RecordData recordData = new RecordData();
		recordData.setUserid(userid);
		recordData.setSequence(sequence);
		recordData.setPileId(pileId);
		recordData.setOrderId(orderId);
		recordData.setData(data);
        recordData.setQuantity(quantity);
		return recordData;
	}
    // KEEP METHODS END

}
