package com.xpg.hssy.db.pojo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.xpg.hssy.engine.LocationInfos.LocationInfo;
import com.xpg.hssy.util.TextUtil;
// KEEP INCLUDES END
/**
 * Entity mapped to table DISTRICT_DATA.
 */
public class DistrictData {

    private Long id;
    private String districtName;
    private String districtPinyin;
    private String districtFirstPinyin;
    private String districtCode;
    private Integer isHot;
    private Long parentId;
    private Long createTime;

    // KEEP FIELDS - put your custom fields here
	{
		parentId = -1L;
		createTime = System.currentTimeMillis();
	}
    // KEEP FIELDS END

    public DistrictData() {
    }

    public DistrictData(Long id) {
        this.id = id;
    }

    public DistrictData(Long id, String districtName, String districtPinyin, String districtFirstPinyin, String districtCode, Integer isHot, Long parentId, Long createTime) {
        this.id = id;
        this.districtName = districtName;
        this.districtPinyin = districtPinyin;
        this.districtFirstPinyin = districtFirstPinyin;
        this.districtCode = districtCode;
        this.isHot = isHot;
        this.parentId = parentId;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDistrictName() {
        return districtName;
    }

    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    public String getDistrictPinyin() {
        return districtPinyin;
    }

    public void setDistrictPinyin(String districtPinyin) {
        this.districtPinyin = districtPinyin;
    }

    public String getDistrictFirstPinyin() {
        return districtFirstPinyin;
    }

    public void setDistrictFirstPinyin(String districtFirstPinyin) {
        this.districtFirstPinyin = districtFirstPinyin;
    }

    public String getDistrictCode() {
        return districtCode;
    }

    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }

    public Integer getIsHot() {
        return isHot;
    }

    public void setIsHot(Integer isHot) {
        this.isHot = isHot;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    // KEEP METHODS - put your custom methods here
	public void setByLocationInfo(LocationInfo locationInfo) {
		districtName = locationInfo.getName();
		districtCode = locationInfo.getCode();
		districtPinyin = TextUtil.getPinyin(districtName);
		districtFirstPinyin = TextUtil.getFirstPinyin(districtName);
	}
    // KEEP METHODS END

}
