package com.xpg.hssy.db.pojo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table KEY.
 */
public class Key implements java.io.Serializable {

    private Long id;
    private String userId;
    private Integer userRole;
    private String pileId;
    private String key;
    private Integer keyType;
    private Long createTime;
    private Long startTime;
    private Long endTime;
    private Long addTime;
    private String orderId;

    // KEEP FIELDS - put your custom fields here
	public static final int TYPE_OWNER = 1;
	public static final int TYPE_FAMILY_OLD = 2;
	public static final int TYPE_ORDER = 3;
	public static final int TYPE_RESET = 4;
	public static final int TYPE_FACTORY = 5;
	public static final int TYPE_FAMILY = 7;
    // KEEP FIELDS END

    public Key() {
    }

    public Key(Long id) {
        this.id = id;
    }

    public Key(Long id, String userId, Integer userRole, String pileId, String key, Integer keyType, Long createTime, Long startTime, Long endTime, Long addTime, String orderId) {
        this.id = id;
        this.userId = userId;
        this.userRole = userRole;
        this.pileId = pileId;
        this.key = key;
        this.keyType = keyType;
        this.createTime = createTime;
        this.startTime = startTime;
        this.endTime = endTime;
        this.addTime = addTime;
        this.orderId = orderId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Integer getUserRole() {
        return userRole;
    }

    public void setUserRole(Integer userRole) {
        this.userRole = userRole;
    }

    public String getPileId() {
        return pileId;
    }

    public void setPileId(String pileId) {
        this.pileId = pileId;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public Integer getKeyType() {
        return keyType;
    }

    public void setKeyType(Integer keyType) {
        this.keyType = keyType;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Long getAddTime() {
        return addTime;
    }

    public void setAddTime(Long addTime) {
        this.addTime = addTime;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
