package com.xpg.hssy.db.pojo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.xpg.hssy.util.TimeUtil;
// KEEP INCLUDES END
/**
 * Entity mapped to table SHARE_TIME.
 */
public class ShareTime implements java.io.Serializable {

    private String id;
    private Long startTime;
    private Long endTime;
    private String pileId;
    private String week;
    private Float servicePay;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ShareTime() {
    }

    public ShareTime(String id) {
        this.id = id;
    }

    public ShareTime(String id, Long startTime, Long endTime, String pileId, String week, Float servicePay) {
        this.id = id;
        this.startTime = startTime;
        this.endTime = endTime;
        this.pileId = pileId;
        this.week = week;
        this.servicePay = servicePay;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public String getPileId() {
        return pileId;
    }

    public void setPileId(String pileId) {
        this.pileId = pileId;
    }

    public String getWeek() {
        return week;
    }

    public void setWeek(String week) {
        this.week = week;
    }

    public Float getServicePay() {
        return servicePay;
    }

    public void setServicePay(Float servicePay) {
        this.servicePay = servicePay;
    }

    // KEEP METHODS - put your custom methods here
	public String getTimeAsString() {
		return getStartTimeAsString() + "-" + getEndTimeAsString();
	}

	public String getStartTimeAsString() {
		return timeLong2String(startTime);
	}

	public void setStartTime(String time) {
		this.startTime = timeString2Long(time);
	}

	public String getEndTimeAsString() {
		String time = timeLong2String(endTime);
		return time.equals("00:00") ? "24:00" : time;
	}

	public void setEndTime(String time) {
		this.endTime = timeString2Long(time);
	}

	private String timeLong2String(Long time) {
		return time == null ? "" : TimeUtil.format(time, "HH:mm");
	}

	private Long timeString2Long(String time) {
		if (time.matches("[0-9]:[0-9][0-9]")) {
			time = "0" + time;
		}

		if (!time.matches("[0-9][0-9]:[0-9][0-9]")) {
			return null;
		}

		return TimeUtil.parse(time, "HH:mm").getTime();
	}

	public List<Integer> getWeeks() {
		if (this.week == null) {
			return null;
		}

		List<Integer> weeks = new ArrayList<Integer>();
		String[] weekArray = this.week.split(",");
		for (String week : weekArray) {
			weeks.add(Integer.parseInt(week));
		}

		return weeks;
	}

	public Set<Integer> createWeeksSet() {
		Set<Integer> weeksSet = new HashSet<>();
		if (this.week == null) {
			return null;
		}
		String[] weekArray = this.week.split(",");
		for (String week : weekArray) {
			weeksSet.add(Integer.parseInt(week));
		}
		return weeksSet;
	}

	public void setWeeks(List<Integer> weeks) {
		if (weeks == null) {
			this.week = null;
			return;
		}

		StringBuilder sb = new StringBuilder();
		for (Integer week : weeks) {
			sb.append(week + ",");
		}
		if (sb.toString().endsWith(",")) {
			sb.deleteCharAt(sb.length() - 1);
		}
		this.week = sb.toString();
	}

	public String getWeeks2String() {
		if (week == null || week.equals("")) {
			return "";
		}
		StringBuilder sb = new StringBuilder();
		String[] weekArray = this.week.split(",");
		for (String week : weekArray) {
			switch (week) {
			case "1":
				sb.append("周日  ");
				break;
			case "2":
				sb.append("周一  ");
				break;
			case "3":
				sb.append("周二  ");
				break;
			case "4":
				sb.append("周三  ");
				break;
			case "5":
				sb.append("周四  ");
				break;
			case "6":
				sb.append("周五  ");
				break;
			case "7":
				sb.append("周六  ");
				break;
			default:
				break;
			}
		}
		return sb.toString();
	}
    // KEEP METHODS END

}
