package com.xpg.hssy.db.pojo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.graphics.Bitmap;
// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
public class User implements java.io.Serializable {

    private String userid;
    private Integer usertype;
    private Boolean contractFlag;
    private String realName;
    private String name;
    private Integer gender;
    private String phone;
    private String alipayName;
    private Long createTime;
    private String token;
    private String refreshToken;
    private String avatarUrl;

    // KEEP FIELDS - put your custom fields here

	public static final int GENDER_MALE = 1;
	public static final int GENDER_FEMALE = 1;
	public static final int USERTYPE_LOGIN_BY_PHONE = 1;
	public static final int USERTYPE_LOGIN_BY_NAME = 2;
	private Bitmap portrait;
    // KEEP FIELDS END

    public User() {
    }

    public User(String userid) {
        this.userid = userid;
    }

    public User(String userid, Integer usertype, Boolean contractFlag, String realName, String name, Integer gender, String phone, String alipayName, Long createTime, String token, String refreshToken, String avatarUrl) {
        this.userid = userid;
        this.usertype = usertype;
        this.contractFlag = contractFlag;
        this.realName = realName;
        this.name = name;
        this.gender = gender;
        this.phone = phone;
        this.alipayName = alipayName;
        this.createTime = createTime;
        this.token = token;
        this.refreshToken = refreshToken;
        this.avatarUrl = avatarUrl;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public Integer getUsertype() {
        return usertype;
    }

    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    public Boolean getContractFlag() {
        return contractFlag;
    }

    public void setContractFlag(Boolean contractFlag) {
        this.contractFlag = contractFlag;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAlipayName() {
        return alipayName;
    }

    public void setAlipayName(String alipayName) {
        this.alipayName = alipayName;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getRefreshToken() {
        return refreshToken;
    }

    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    // KEEP METHODS - put your custom methods here

	public void update(User newUser) {
		setAvatarUrl(newUser.getAvatarUrl());
		// setCreateTime(newUser.getCreateTime());
		setGender(newUser.getGender());
		setName(newUser.getName());
		setPhone(newUser.getPhone());
		setPortrait(newUser.getPortrait());
		setRealName(newUser.getRealName());
		setUserid(newUser.getUserid());
		setUsertype(newUser.getUsertype());
	}

	public Bitmap getPortrait() {
		return portrait;
	}

	public void setPortrait(Bitmap portrait) {
		this.portrait = portrait;
	}
    // KEEP METHODS END

}
